BEGIN TRANSACTION;
CREATE TABLE "barang" (
	"id_barang"	INTEGER,
	"nama_barang"	TEXT NOT NULL,
	"kategori"	TEXT NOT NULL,
	"stok"	INTEGER NOT NULL,
	"harga"	INTEGER NOT NULL,
	"cocok_untuk"	TEXT NOT NULL,
	PRIMARY KEY("id_barang" AUTOINCREMENT)
);
INSERT INTO "barang" VALUES(1,'Oli Yamalube Matic','oli',15,65000,'mio, fino, beat, vario, scoopy');
INSERT INTO "barang" VALUES(2,'Oli AHM MPX 2','oli',12,70000,'beat, vario, scoopy, pcx');
INSERT INTO "barang" VALUES(3,'Oli Enduro Matic','oli',10,68000,'mio, nmax, aerox');
INSERT INTO "barang" VALUES(4,'Busi NGK CPR9EA','busi',18,25000,'beat, vario, scoopy');
INSERT INTO "barang" VALUES(5,'Busi Denso U22EPR9','busi',18,28000,'mio, fino, lexi');
INSERT INTO "barang" VALUES(6,'Aki GS Astra GTZ5S','aki',8,260000,'beat, scoopy, vario');
INSERT INTO "barang" VALUES(7,'Aki Yuasa YTZ5S','aki',6,280000,'beat, vario, pcx');
INSERT INTO "barang" VALUES(8,'Ban FDR Sport XR Evo','ban',10,250000,'beat, vario, scoopy');
INSERT INTO "barang" VALUES(9,'Ban IRC NR76','ban',9,230000,'mio, fino, beat');
INSERT INTO "barang" VALUES(10,'Kampas Rem Federal','kampas rem',25,45000,'beat, vario, scoopy');
INSERT INTO "barang" VALUES(11,'Kampas Rem Indoparts','kampas rem',20,40000,'mio, fino');
INSERT INTO "barang" VALUES(12,'Filter Udara Honda','filter udara',10,35000,'beat, vario, scoopy');
INSERT INTO "barang" VALUES(13,'Filter Udara Yamaha','filter udara',8,38000,'mio, fino, nmax');
INSERT INTO "barang" VALUES(14,'CVT Belt Bando','cvt',7,120000,'beat, vario, scoopy');
INSERT INTO "barang" VALUES(15,'Rantai SSS','rantai',12,150000,'supra, jupiter, vega');
INSERT INTO "barang" VALUES(16,'Knalpot Racing Proliner','knalpot',6,450000,'mio, beat, vario');
INSERT INTO "barang" VALUES(17,'Knalpot Standar','knalpot',5,250000,'beat, vario, scoopy');
INSERT INTO "barang" VALUES(18,'Spion Mio','spion',12,32000,'mio, fino, nmax, aerox');
INSERT INTO "barang" VALUES(19,'Spion Vario 125','spion',8,35000,'vario, beat, scoopy, pcx');
INSERT INTO "barang" VALUES(20,'Filter Oli AHM','filter oli',15,28000,'beat, vario, scoopy, pcx');
INSERT INTO "barang" VALUES(21,'Filter Oli Yamalube','filter oli',10,30000,'mio, nmax, aerox');
INSERT INTO "barang" VALUES(22,'Kampas Kopling Matic','kampas kopling',7,90000,'mio, beat, vario, scoopy, nmax');
INSERT INTO "barang" VALUES(23,'Kampas Kopling Bebek','kampas kopling',6,85000,'supra, jupiter, vega');
INSERT INTO "barang" VALUES(24,'Roller CVT 15x12','roller',14,45000,'mio, beat, scoopy');
INSERT INTO "barang" VALUES(25,'Roller CVT 16x13','roller',10,47000,'vario, nmax, aerox, pcx');
INSERT INTO "barang" VALUES(26,'CDI Yamaha Mio','cdi',5,150000,'mio, fino');
INSERT INTO "barang" VALUES(27,'CDI Honda Beat','cdi',4,155000,'beat, scoopy');
INSERT INTO "barang" VALUES(28,'Kabel Busi','sparepart',20,20000,'supra, jupiter, vega, beat, mio');
INSERT INTO "barang" VALUES(29,'Kabel Kopling','sparepart',18,25000,'vixion, cb150r, supra');
INSERT INTO "barang" VALUES(30,'Karet Gas','sparepart',15,17000,'mio, beat, vario, scoopy, supra');
INSERT INTO "barang" VALUES(31,'Switch Starter','switch',10,40000,'beat, vario, scoopy, mio');
INSERT INTO "barang" VALUES(32,'Relay Starter','switch',5,50000,'nmax, pcx, vario');
INSERT INTO "barang" VALUES(33,'Karburator Yamaha','karburator',2,325000,'mio, jupiter, vega');
INSERT INTO "barang" VALUES(34,'Karburator Honda','karburator',3,340000,'beat, supra, revo');
INSERT INTO "barang" VALUES(35,'Rantai SSS 428','rantai',9,155000,'supra, jupiter, vega, rx king');
INSERT INTO "barang" VALUES(36,'Velg Depan','velg',2,400000,'mio, beat, vario, scoopy');
INSERT INTO "barang" VALUES(37,'Velg Belakang','velg',2,450000,'mio, beat, vario, scoopy');
INSERT INTO "barang" VALUES(38,'Lampu Depan LED','lampu',10,120000,'beat, vario, scoopy, mio, nmax');
INSERT INTO "barang" VALUES(39,'Lampu Sen LED','lampu',10,45000,'beat, vario, scoopy, mio, nmax, pcx');
INSERT INTO "barang" VALUES(40,'Kampas Rem Cakram','rem cakram',12,65000,'beat, vario, scoopy, mio, nmax, pcx');
INSERT INTO "barang" VALUES(41,'Cakram Depan','rem cakram',4,120000,'beat, vario, scoopy, mio');
INSERT INTO "barang" VALUES(42,'Master Rem Depan','rem cakram',3,175000,'beat, vario, mio, nmax');
INSERT INTO "barang" VALUES(43,'Shockbreaker Depan','sparepart',6,250000,'beat, vario, scoopy, mio');
INSERT INTO "barang" VALUES(44,'Shockbreaker Belakang','sparepart',5,270000,'beat, vario, scoopy, mio, nmax');
INSERT INTO "barang" VALUES(45,'Busi NGK KR7A','busi',15,26000,'beat, vario, scoopy');
INSERT INTO "barang" VALUES(46,'Aki Yuasa YTX7A-BS','aki',5,300000,'nmax, pcx, aerox');
INSERT INTO "barang" VALUES(47,'Busi NGK CPR','busi',5,30000,'beat, mio, revo');
INSERT INTO "barang" VALUES(48,'Starter HT56','starter motor',3,20000,'scoopy, pcx');
CREATE TABLE "chatbot_data" (
	"id_chatbot"	INTEGER,
	"intent"	TEXT NOT NULL,
	"pertanyaan"	TEXT NOT NULL,
	"jawaban"	TEXT NOT NULL,
	"action"	TEXT,
	PRIMARY KEY("id_chatbot" AUTOINCREMENT)
);
INSERT INTO "chatbot_data" VALUES(1,'sapaan','halo','Halo! Ada yang bisa saya bantu terkait layanan Bengkel Motor Kurnia?','');
INSERT INTO "chatbot_data" VALUES(2,'sapaan','hai','Halo! Ada yang bisa saya bantu terkait layanan Bengkel Motor Kurnia?','');
INSERT INTO "chatbot_data" VALUES(3,'sapaan','hallo','Halo! Ada yang bisa saya bantu terkait layanan Bengkel Motor Kurnia?','');
INSERT INTO "chatbot_data" VALUES(4,'sapaan','selamat pagi','Selamat pagi, ada yang bisa kami bantu?','');
INSERT INTO "chatbot_data" VALUES(5,'sapaan','selamat siang','Selamat siang, silakan tanyakan kebutuhan Anda.','');
INSERT INTO "chatbot_data" VALUES(6,'sapaan','selamat sore','Selamat sore, ada yang bisa dibantu?','');
INSERT INTO "chatbot_data" VALUES(7,'sapaan','permisi','Halo, silakan tanyakan kebutuhan Anda.','');
INSERT INTO "chatbot_data" VALUES(8,'sapaan','assalamualaikum','Waalaikumsalam, ada yang bisa dibantu?','');
INSERT INTO "chatbot_data" VALUES(9,'sapaan','salam','Halo, selamat datang di Bengkel Motor Kurnia.','');
INSERT INTO "chatbot_data" VALUES(10,'sapaan','pagi bengkel','Selamat pagi, ada yang bisa dibantu?','');
INSERT INTO "chatbot_data" VALUES(11,'sapaan','halo bengkel','Halo! Ada yang bisa saya bantu terkait layanan bengkel?','');
INSERT INTO "chatbot_data" VALUES(12,'sapaan','hai admin','Halo! Silakan tanyakan kebutuhan Anda.','');
INSERT INTO "chatbot_data" VALUES(13,'sapaan','selamat malam','Halo, pesan Anda tetap dapat ditanyakan melalui chatbot ini.','');
INSERT INTO "chatbot_data" VALUES(14,'sapaan','punten bengkel','Halo, silakan tanyakan kebutuhan Anda.','');
INSERT INTO "chatbot_data" VALUES(15,'bantuan_umum','tolong bantu saya','Saya dapat membantu informasi bengkel, jadwal, lokasi, servis, stok barang, dan rekomendasi produk.','');
INSERT INTO "chatbot_data" VALUES(16,'bantuan_umum','bantu saya','Saya dapat membantu informasi bengkel, jadwal, lokasi, servis, stok barang, dan rekomendasi produk.','');
INSERT INTO "chatbot_data" VALUES(17,'bantuan_umum','bisa bantu saya','Tentu, silakan tanyakan kebutuhan Anda terkait bengkel motor.','');
INSERT INTO "chatbot_data" VALUES(18,'bantuan_umum','saya butuh bantuan','Silakan tanyakan layanan bengkel yang Anda butuhkan.','');
INSERT INTO "chatbot_data" VALUES(19,'bantuan_umum','bantu dong','Silakan tanyakan kebutuhan Anda terkait bengkel motor.','');
INSERT INTO "chatbot_data" VALUES(20,'bantuan_umum','chatbot ini bisa apa','Saya dapat membantu lokasi bengkel, jadwal, servis motor, stok barang, dan rekomendasi produk.','');
INSERT INTO "chatbot_data" VALUES(21,'bantuan_umum','fitur chatbot apa saja','Saya dapat membantu lokasi bengkel, jadwal, servis motor, stok barang, dan rekomendasi produk.','');
INSERT INTO "chatbot_data" VALUES(22,'bantuan_umum','kamu bisa bantu apa','Saya dapat membantu informasi bengkel, stok barang, dan keluhan motor sederhana.','');
INSERT INTO "chatbot_data" VALUES(23,'bantuan_umum','saya mau tanya','Silakan tanyakan kebutuhan Anda terkait bengkel motor.','');
INSERT INTO "chatbot_data" VALUES(24,'bantuan_umum','mau tanya dong','Silakan tanyakan kebutuhan Anda terkait bengkel motor.','');
INSERT INTO "chatbot_data" VALUES(25,'bantuan_umum','butuh informasi bengkel','Saya dapat membantu informasi bengkel, jadwal, lokasi, servis, stok barang, dan rekomendasi produk.','');
INSERT INTO "chatbot_data" VALUES(26,'bantuan_umum','help','Silakan tanyakan kebutuhan Anda terkait bengkel motor.','');
INSERT INTO "chatbot_data" VALUES(27,'bantuan_umum','ada yang bisa dibantu','Saya dapat membantu informasi bengkel, jadwal, lokasi, servis, stok barang, dan rekomendasi produk.','');
INSERT INTO "chatbot_data" VALUES(28,'bantuan_umum','informasi apa saja yang tersedia','Saya dapat membantu lokasi bengkel, jadwal, servis motor, stok barang, dan rekomendasi produk.','');
INSERT INTO "chatbot_data" VALUES(29,'akhir_percakapan','terima kasih','Sama-sama, semoga membantu.','');
INSERT INTO "chatbot_data" VALUES(30,'akhir_percakapan','makasih','Sama-sama, hati-hati di jalan.','');
INSERT INTO "chatbot_data" VALUES(31,'akhir_percakapan','matur nuwun','Sama-sama, semoga membantu.','');
INSERT INTO "chatbot_data" VALUES(32,'akhir_percakapan','sudah cukup','Baik, terima kasih telah menggunakan layanan chatbot bengkel.','');
INSERT INTO "chatbot_data" VALUES(33,'akhir_percakapan','cukup','Baik, semoga informasi yang diberikan membantu.','');
INSERT INTO "chatbot_data" VALUES(34,'akhir_percakapan','itu saja','Baik, terima kasih sudah menghubungi bengkel kami.','');
INSERT INTO "chatbot_data" VALUES(35,'akhir_percakapan','tidak ada pertanyaan lagi','Baik, terima kasih sudah menghubungi bengkel kami.','');
INSERT INTO "chatbot_data" VALUES(36,'akhir_percakapan','sudah jelas','Baik, terima kasih telah menggunakan layanan chatbot bengkel.','');
INSERT INTO "chatbot_data" VALUES(37,'akhir_percakapan','oke makasih','Sama-sama, semoga harimu menyenangkan.','');
INSERT INTO "chatbot_data" VALUES(38,'akhir_percakapan','bye','Terima kasih telah menggunakan layanan chatbot bengkel.','');
INSERT INTO "chatbot_data" VALUES(39,'akhir_percakapan','sampai jumpa','Sampai jumpa kembali.','');
INSERT INTO "chatbot_data" VALUES(40,'akhir_percakapan','ok sip','Baik, semoga informasi yang diberikan membantu.','');
INSERT INTO "chatbot_data" VALUES(41,'jadwal_bengkel','bengkel buka jam berapa','Bengkel buka pukul 08.00-17.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(42,'jadwal_bengkel','jam operasional bengkel','Bengkel buka Senin-Sabtu pukul 08.00-17.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(43,'jadwal_bengkel','hari ini buka tidak','Bengkel buka Senin-Sabtu pukul 08.00-17.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(44,'jadwal_bengkel','buka sampai jam berapa','Bengkel melayani sampai pukul 17.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(45,'jadwal_bengkel','bengkel tutup jam berapa','Bengkel tutup pukul 17.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(46,'jadwal_bengkel','hari minggu buka tidak','Bengkel libur pada hari Minggu.','');
INSERT INTO "chatbot_data" VALUES(47,'jadwal_bengkel','sabtu buka tidak','Bengkel buka hari Senin-Sabtu.','');
INSERT INTO "chatbot_data" VALUES(48,'jadwal_bengkel','bisa servis sore','Bengkel melayani servis sampai pukul 17.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(49,'jadwal_bengkel','jadwal bengkel gimana','Bengkel buka Senin-Sabtu pukul 08.00-17.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(50,'jadwal_bengkel','buka dari pagi jam berapa','Bengkel buka mulai pukul 08.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(51,'jadwal_bengkel','bengkel libur hari apa','Bengkel libur hari Minggu.','');
INSERT INTO "chatbot_data" VALUES(52,'jadwal_bengkel','masih buka sekarang','Bengkel buka sampai pukul 17.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(53,'lokasi_bengkel','alamat bengkel dimana','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(54,'lokasi_bengkel','lokasi bengkel dimana','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(55,'lokasi_bengkel','bengkel ada dimana','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(56,'lokasi_bengkel','share lokasi bengkel','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(57,'lokasi_bengkel','ada maps bengkel','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(58,'lokasi_bengkel','kirim alamat bengkel','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(59,'lokasi_bengkel','bengkel dekat mana','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(60,'lokasi_bengkel','rute ke bengkel gimana','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(61,'lokasi_bengkel','posisi bengkel dimana','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(62,'lokasi_bengkel','lokasi lengkap bengkel','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(63,'lokasi_bengkel','maps kurnia motor','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(64,'lokasi_bengkel','saya mau ke bengkel','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(65,'kontak_admin','nomor wa bengkel berapa','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(66,'kontak_admin','wa bengkel berapa','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(67,'kontak_admin','nomor whatsapp bengkel','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(68,'kontak_admin','bisa hubungi lewat whatsapp','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(69,'kontak_admin','kontak admin ada','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(70,'kontak_admin','nomor telepon bengkel','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(71,'kontak_admin','minta nomor admin','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(72,'kontak_admin','saya mau chat petugas','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(73,'kontak_admin','hubungi petugas bengkel','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(74,'kontak_admin','nomor bengkel berapa','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(75,'kontak_admin','kontak bengkel','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(76,'kontak_admin','admin bisa dihubungi','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(77,'harga_servis','ganti oli motor berapa','Biaya ganti oli mulai Rp50.000, belum termasuk harga oli tertentu.','');
INSERT INTO "chatbot_data" VALUES(78,'harga_servis','servis motor berapa','Biaya servis motor mulai dari Rp75.000.','');
INSERT INTO "chatbot_data" VALUES(79,'harga_servis','servis lengkap habis berapa','Biaya servis lengkap mulai dari Rp150.000.','');
INSERT INTO "chatbot_data" VALUES(80,'harga_servis','tune up motor berapa','Biaya tune up mulai dari Rp100.000.','');
INSERT INTO "chatbot_data" VALUES(81,'harga_servis','servis ringan berapa','Biaya servis ringan mulai dari Rp75.000.','');
INSERT INTO "chatbot_data" VALUES(82,'harga_servis','cek motor bayar tidak','Pengecekan motor gratis.','');
INSERT INTO "chatbot_data" VALUES(83,'harga_servis','biaya cek kerusakan motor','Pengecekan motor gratis.','');
INSERT INTO "chatbot_data" VALUES(84,'harga_servis','tarif servis matic','Biaya servis motor matic mulai dari Rp75.000.','');
INSERT INTO "chatbot_data" VALUES(85,'harga_servis','harga servis injeksi','Biaya servis injeksi menyesuaikan kondisi motor.','');
INSERT INTO "chatbot_data" VALUES(86,'harga_servis','berapa biaya perbaikan rem','Biaya perbaikan rem menyesuaikan kondisi dan sparepart.','');
INSERT INTO "chatbot_data" VALUES(87,'harga_servis','biaya ganti ban','Biaya penggantian ban menyesuaikan jenis ban.','');
INSERT INTO "chatbot_data" VALUES(88,'harga_servis','harga tune up bengkel','Biaya tune up mulai dari Rp100.000.','');
INSERT INTO "chatbot_data" VALUES(89,'layanan_servis','motor saya brebet','Sedang menganalisis keluhan motor.','diagnosa');
INSERT INTO "chatbot_data" VALUES(90,'layanan_servis','motor brebet saat digas','Sedang menganalisis keluhan motor.','diagnosa');
INSERT INTO "chatbot_data" VALUES(91,'layanan_servis','motor brebet di tanjakan','Sedang menganalisis keluhan motor.','diagnosa');
INSERT INTO "chatbot_data" VALUES(92,'layanan_servis','motor brebet saat dingin','Sedang menganalisis keluhan motor.','diagnosa');
INSERT INTO "chatbot_data" VALUES(93,'layanan_servis','motor susah hidup','Sedang menganalisis keluhan motor.','diagnosa');
INSERT INTO "chatbot_data" VALUES(94,'layanan_servis','rem motor keras','Sedang menganalisis keluhan motor.','diagnosa');
INSERT INTO "chatbot_data" VALUES(95,'layanan_servis','mesin motor cepat panas','Sedang menganalisis keluhan motor.','diagnosa');
INSERT INTO "chatbot_data" VALUES(96,'layanan_servis','bisa servis motor matic','Bengkel melayani servis motor matic.','');
INSERT INTO "chatbot_data" VALUES(97,'layanan_servis','bisa servis injeksi','Bengkel menerima servis injeksi.','');
INSERT INTO "chatbot_data" VALUES(98,'layanan_servis','bisa tune up motor','Bengkel melayani tune up motor.','');
INSERT INTO "chatbot_data" VALUES(99,'layanan_servis','bisa ganti ban','Bengkel melayani penggantian ban.','');
INSERT INTO "chatbot_data" VALUES(100,'layanan_servis','bisa ganti oli','Bengkel melayani penggantian oli.','');
INSERT INTO "chatbot_data" VALUES(101,'layanan_servis','bisa perbaiki rem motor','Bengkel melayani perbaikan rem motor.','');
INSERT INTO "chatbot_data" VALUES(102,'layanan_servis','servis motor karburator bisa','Bengkel melayani servis motor karburator.','');
INSERT INTO "chatbot_data" VALUES(103,'layanan_servis','servis motor beat bisa','Bengkel melayani servis motor Beat.','');
INSERT INTO "chatbot_data" VALUES(104,'layanan_servis','servis motor vario bisa','Bengkel melayani servis motor Vario.','');
INSERT INTO "chatbot_data" VALUES(105,'cek_stok','stok oli yamalube matic','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(106,'cek_stok','ada oli ahm mpx 2','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(107,'cek_stok','oli enduro matic ready','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(108,'cek_stok','stok busi ngk cpr9ea','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(109,'cek_stok','ada busi denso u22epr9','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(110,'cek_stok','stok aki gs astra','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(111,'cek_stok','aki yuasa masih ada','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(112,'cek_stok','ban fdr ready','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(113,'cek_stok','ban irc masih tersedia','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(114,'cek_stok','kampas rem federal ada','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(115,'cek_stok','kampas rem indoparts ready','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(116,'cek_stok','filter udara honda ada','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(117,'cek_stok','filter udara yamaha tersedia','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(118,'cek_stok','cvt belt bando ada','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(119,'cek_stok','rantai sss ready','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(120,'cek_stok','stok oli untuk beat','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(121,'cek_stok','stok busi untuk vario','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(122,'cek_stok','stok aki untuk scoopy','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(123,'info_barang','informasi oli yamalube matic','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(124,'info_barang','harga oli ahm mpx 2','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(125,'info_barang','detail oli enduro matic','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(126,'info_barang','info busi ngk cpr9ea','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(127,'info_barang','harga busi denso u22epr9','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(128,'info_barang','informasi aki gs astra','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(129,'info_barang','detail aki yuasa','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(130,'info_barang','harga ban fdr sport','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(131,'info_barang','info ban irc nr76','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(132,'info_barang','harga kampas rem federal','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(133,'info_barang','detail kampas rem indoparts','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(134,'info_barang','info filter udara honda','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(135,'info_barang','harga filter udara yamaha','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(136,'info_barang','detail cvt belt bando','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(137,'info_barang','harga rantai sss','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(138,'info_barang','harga oli untuk beat','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(139,'info_barang','info aki untuk vario','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(140,'info_barang','detail sparepart motor','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(141,'rekom_produk','oli yang cocok untuk beat','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(142,'rekom_produk','rekomendasi oli vario','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(143,'rekom_produk','oli bagus untuk scoopy','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(144,'rekom_produk','oli untuk motor matic','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(145,'rekom_produk','busi yang cocok untuk beat','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(146,'rekom_produk','busi untuk vario apa','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(147,'rekom_produk','aki terbaik untuk nmax','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(148,'rekom_produk','aki untuk pcx apa','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(149,'rekom_produk','ban yang cocok untuk beat','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(150,'rekom_produk','produk cocok untuk mio','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(151,'daftar_barang','oli yang tersedia ada apa saja','Berikut daftar oli yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(152,'daftar_barang','oli apa saja yang ada','Berikut daftar oli yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(153,'daftar_barang','daftar oli yang tersedia','Berikut daftar oli yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(154,'daftar_barang','pilihan oli di bengkel apa saja','Berikut daftar oli yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(155,'daftar_barang','busi yang tersedia ada apa saja','Berikut daftar busi yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(156,'daftar_barang','daftar aki yang ada','Berikut daftar aki yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(157,'daftar_barang','ban apa saja yang tersedia','Berikut daftar ban yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(158,'daftar_barang','sparepart yang tersedia apa saja','Berikut daftar sparepart yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(159,'daftar_barang','barang yang tersedia di bengkel apa saja','Berikut daftar barang yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(160,'daftar_barang','ada pilihan filter udara apa saja','Berikut daftar filter udara yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(161,'sapaan','halo min','Halo! Ada yang bisa saya bantu terkait layanan Bengkel Motor Kurnia?','');
INSERT INTO "chatbot_data" VALUES(162,'sapaan','hai min','Halo! Ada yang bisa saya bantu terkait layanan Bengkel Motor Kurnia?','');
INSERT INTO "chatbot_data" VALUES(163,'sapaan','hallo min','Halo! Ada yang bisa saya bantu terkait layanan Bengkel Motor Kurnia?','');
INSERT INTO "chatbot_data" VALUES(164,'sapaan','selamat pagi min','Selamat pagi, ada yang bisa kami bantu?','');
INSERT INTO "chatbot_data" VALUES(165,'sapaan','selamat siang min','Selamat siang, silakan tanyakan kebutuhan Anda.','');
INSERT INTO "chatbot_data" VALUES(166,'sapaan','selamat sore min','Selamat sore, ada yang bisa dibantu?','');
INSERT INTO "chatbot_data" VALUES(167,'sapaan','permisi min','Halo, silakan tanyakan kebutuhan Anda.','');
INSERT INTO "chatbot_data" VALUES(168,'sapaan','assalamualaikum min','Waalaikumsalam, ada yang bisa dibantu?','');
INSERT INTO "chatbot_data" VALUES(169,'sapaan','salam min','Halo, selamat datang di Bengkel Motor Kurnia.','');
INSERT INTO "chatbot_data" VALUES(170,'sapaan','pagi bengkel min','Selamat pagi, ada yang bisa dibantu?','');
INSERT INTO "chatbot_data" VALUES(171,'sapaan','halo bengkel min','Halo! Ada yang bisa saya bantu terkait layanan bengkel?','');
INSERT INTO "chatbot_data" VALUES(172,'sapaan','hai admin min','Halo! Silakan tanyakan kebutuhan Anda.','');
INSERT INTO "chatbot_data" VALUES(173,'sapaan','selamat malam min','Halo, pesan Anda tetap dapat ditanyakan melalui chatbot ini.','');
INSERT INTO "chatbot_data" VALUES(174,'sapaan','punten bengkel min','Halo, silakan tanyakan kebutuhan Anda.','');
INSERT INTO "chatbot_data" VALUES(175,'bantuan_umum','min, tolong bantu saya','Saya dapat membantu informasi bengkel, jadwal, lokasi, servis, stok barang, dan rekomendasi produk.','');
INSERT INTO "chatbot_data" VALUES(176,'bantuan_umum','min, bantu saya','Saya dapat membantu informasi bengkel, jadwal, lokasi, servis, stok barang, dan rekomendasi produk.','');
INSERT INTO "chatbot_data" VALUES(177,'bantuan_umum','min, bisa bantu saya','Tentu, silakan tanyakan kebutuhan Anda terkait bengkel motor.','');
INSERT INTO "chatbot_data" VALUES(178,'bantuan_umum','min, saya butuh bantuan','Silakan tanyakan layanan bengkel yang Anda butuhkan.','');
INSERT INTO "chatbot_data" VALUES(179,'bantuan_umum','min, bantu dong','Silakan tanyakan kebutuhan Anda terkait bengkel motor.','');
INSERT INTO "chatbot_data" VALUES(180,'bantuan_umum','min, chatbot ini bisa apa','Saya dapat membantu lokasi bengkel, jadwal, servis motor, stok barang, dan rekomendasi produk.','');
INSERT INTO "chatbot_data" VALUES(181,'bantuan_umum','min, fitur chatbot apa saja','Saya dapat membantu lokasi bengkel, jadwal, servis motor, stok barang, dan rekomendasi produk.','');
INSERT INTO "chatbot_data" VALUES(182,'bantuan_umum','min, kamu bisa bantu apa','Saya dapat membantu informasi bengkel, stok barang, dan keluhan motor sederhana.','');
INSERT INTO "chatbot_data" VALUES(183,'bantuan_umum','min, saya mau tanya','Silakan tanyakan kebutuhan Anda terkait bengkel motor.','');
INSERT INTO "chatbot_data" VALUES(184,'bantuan_umum','min, mau tanya dong','Silakan tanyakan kebutuhan Anda terkait bengkel motor.','');
INSERT INTO "chatbot_data" VALUES(185,'bantuan_umum','min, butuh informasi bengkel','Saya dapat membantu informasi bengkel, jadwal, lokasi, servis, stok barang, dan rekomendasi produk.','');
INSERT INTO "chatbot_data" VALUES(186,'bantuan_umum','min, help','Silakan tanyakan kebutuhan Anda terkait bengkel motor.','');
INSERT INTO "chatbot_data" VALUES(187,'bantuan_umum','min, ada yang bisa dibantu','Saya dapat membantu informasi bengkel, jadwal, lokasi, servis, stok barang, dan rekomendasi produk.','');
INSERT INTO "chatbot_data" VALUES(188,'bantuan_umum','min, informasi apa saja yang tersedia','Saya dapat membantu lokasi bengkel, jadwal, servis motor, stok barang, dan rekomendasi produk.','');
INSERT INTO "chatbot_data" VALUES(189,'akhir_percakapan','terima kasih ya','Sama-sama, semoga membantu.','');
INSERT INTO "chatbot_data" VALUES(190,'akhir_percakapan','makasih ya','Sama-sama, hati-hati di jalan.','');
INSERT INTO "chatbot_data" VALUES(191,'akhir_percakapan','matur nuwun ya','Sama-sama, semoga membantu.','');
INSERT INTO "chatbot_data" VALUES(192,'akhir_percakapan','sudah cukup ya','Baik, terima kasih telah menggunakan layanan chatbot bengkel.','');
INSERT INTO "chatbot_data" VALUES(193,'akhir_percakapan','cukup ya','Baik, semoga informasi yang diberikan membantu.','');
INSERT INTO "chatbot_data" VALUES(194,'akhir_percakapan','itu saja ya','Baik, terima kasih sudah menghubungi bengkel kami.','');
INSERT INTO "chatbot_data" VALUES(195,'akhir_percakapan','tidak ada pertanyaan lagi ya','Baik, terima kasih sudah menghubungi bengkel kami.','');
INSERT INTO "chatbot_data" VALUES(196,'akhir_percakapan','sudah jelas ya','Baik, terima kasih telah menggunakan layanan chatbot bengkel.','');
INSERT INTO "chatbot_data" VALUES(197,'akhir_percakapan','oke makasih ya','Sama-sama, semoga harimu menyenangkan.','');
INSERT INTO "chatbot_data" VALUES(198,'akhir_percakapan','bye ya','Terima kasih telah menggunakan layanan chatbot bengkel.','');
INSERT INTO "chatbot_data" VALUES(199,'akhir_percakapan','sampai jumpa ya','Sampai jumpa kembali.','');
INSERT INTO "chatbot_data" VALUES(200,'akhir_percakapan','ok sip ya','Baik, semoga informasi yang diberikan membantu.','');
INSERT INTO "chatbot_data" VALUES(201,'jadwal_bengkel','min, bengkel buka jam berapa','Bengkel buka pukul 08.00-17.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(202,'jadwal_bengkel','min, jam operasional bengkel','Bengkel buka Senin-Sabtu pukul 08.00-17.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(203,'jadwal_bengkel','min, hari ini buka tidak','Bengkel buka Senin-Sabtu pukul 08.00-17.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(204,'jadwal_bengkel','min, buka sampai jam berapa','Bengkel melayani sampai pukul 17.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(205,'jadwal_bengkel','min, bengkel tutup jam berapa','Bengkel tutup pukul 17.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(206,'jadwal_bengkel','min, hari minggu buka tidak','Bengkel libur pada hari Minggu.','');
INSERT INTO "chatbot_data" VALUES(207,'jadwal_bengkel','min, sabtu buka tidak','Bengkel buka hari Senin-Sabtu.','');
INSERT INTO "chatbot_data" VALUES(208,'jadwal_bengkel','min, bisa servis sore','Bengkel melayani servis sampai pukul 17.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(209,'jadwal_bengkel','min, jadwal bengkel gimana','Bengkel buka Senin-Sabtu pukul 08.00-17.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(210,'jadwal_bengkel','min, buka dari pagi jam berapa','Bengkel buka mulai pukul 08.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(211,'jadwal_bengkel','min, bengkel libur hari apa','Bengkel libur hari Minggu.','');
INSERT INTO "chatbot_data" VALUES(212,'jadwal_bengkel','min, masih buka sekarang','Bengkel buka sampai pukul 17.00 WIB.','');
INSERT INTO "chatbot_data" VALUES(213,'lokasi_bengkel','alamat bengkel dimana min','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(214,'lokasi_bengkel','lokasi bengkel dimana min','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(215,'lokasi_bengkel','bengkel ada dimana min','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(216,'lokasi_bengkel','share lokasi bengkel min','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(217,'lokasi_bengkel','ada maps bengkel min','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(218,'lokasi_bengkel','kirim alamat bengkel min','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(219,'lokasi_bengkel','bengkel dekat mana min','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(220,'lokasi_bengkel','rute ke bengkel gimana min','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(221,'lokasi_bengkel','posisi bengkel dimana min','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(222,'lokasi_bengkel','lokasi lengkap bengkel min','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(223,'lokasi_bengkel','maps kurnia motor min','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(224,'lokasi_bengkel','saya mau ke bengkel min','Bengkel berada di depan Masjid Senduro.','open_maps');
INSERT INTO "chatbot_data" VALUES(225,'kontak_admin','min, nomor wa bengkel berapa','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(226,'kontak_admin','min, wa bengkel berapa','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(227,'kontak_admin','min, nomor whatsapp bengkel','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(228,'kontak_admin','min, bisa hubungi lewat whatsapp','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(229,'kontak_admin','min, kontak admin ada','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(230,'kontak_admin','min, nomor telepon bengkel','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(231,'kontak_admin','min, minta nomor admin','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(232,'kontak_admin','min, saya mau chat petugas','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(233,'kontak_admin','min, hubungi petugas bengkel','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(234,'kontak_admin','min, nomor bengkel berapa','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(235,'kontak_admin','min, kontak bengkel','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(236,'kontak_admin','min, admin bisa dihubungi','Nomor WhatsApp kami adalah 085606213825.','open_wa');
INSERT INTO "chatbot_data" VALUES(237,'harga_servis','ganti oli motor berapa ya','Biaya ganti oli mulai Rp50.000, belum termasuk harga oli tertentu.','');
INSERT INTO "chatbot_data" VALUES(238,'harga_servis','servis motor berapa ya','Biaya servis motor mulai dari Rp75.000.','');
INSERT INTO "chatbot_data" VALUES(239,'harga_servis','servis lengkap habis berapa ya','Biaya servis lengkap mulai dari Rp150.000.','');
INSERT INTO "chatbot_data" VALUES(240,'harga_servis','tune up motor berapa ya','Biaya tune up mulai dari Rp100.000.','');
INSERT INTO "chatbot_data" VALUES(241,'harga_servis','servis ringan berapa ya','Biaya servis ringan mulai dari Rp75.000.','');
INSERT INTO "chatbot_data" VALUES(242,'harga_servis','cek motor bayar tidak ya','Pengecekan motor gratis.','');
INSERT INTO "chatbot_data" VALUES(243,'harga_servis','biaya cek kerusakan motor ya','Pengecekan motor gratis.','');
INSERT INTO "chatbot_data" VALUES(244,'harga_servis','tarif servis matic ya','Biaya servis motor matic mulai dari Rp75.000.','');
INSERT INTO "chatbot_data" VALUES(245,'harga_servis','harga servis injeksi ya','Biaya servis injeksi menyesuaikan kondisi motor.','');
INSERT INTO "chatbot_data" VALUES(246,'harga_servis','berapa biaya perbaikan rem ya','Biaya perbaikan rem menyesuaikan kondisi dan sparepart.','');
INSERT INTO "chatbot_data" VALUES(247,'harga_servis','biaya ganti ban ya','Biaya penggantian ban menyesuaikan jenis ban.','');
INSERT INTO "chatbot_data" VALUES(248,'harga_servis','harga tune up bengkel ya','Biaya tune up mulai dari Rp100.000.','');
INSERT INTO "chatbot_data" VALUES(249,'layanan_servis','min, motor saya brebet','Sedang menganalisis keluhan motor.','diagnosa');
INSERT INTO "chatbot_data" VALUES(250,'layanan_servis','min, motor brebet saat digas','Sedang menganalisis keluhan motor.','diagnosa');
INSERT INTO "chatbot_data" VALUES(251,'layanan_servis','min, motor brebet di tanjakan','Sedang menganalisis keluhan motor.','diagnosa');
INSERT INTO "chatbot_data" VALUES(252,'layanan_servis','min, motor brebet saat dingin','Sedang menganalisis keluhan motor.','diagnosa');
INSERT INTO "chatbot_data" VALUES(253,'layanan_servis','min, motor susah hidup','Sedang menganalisis keluhan motor.','diagnosa');
INSERT INTO "chatbot_data" VALUES(254,'layanan_servis','min, rem motor keras','Sedang menganalisis keluhan motor.','diagnosa');
INSERT INTO "chatbot_data" VALUES(255,'layanan_servis','min, mesin motor cepat panas','Sedang menganalisis keluhan motor.','diagnosa');
INSERT INTO "chatbot_data" VALUES(256,'layanan_servis','min, bisa servis motor matic','Bengkel melayani servis motor matic.','');
INSERT INTO "chatbot_data" VALUES(257,'layanan_servis','min, bisa servis injeksi','Bengkel menerima servis injeksi.','');
INSERT INTO "chatbot_data" VALUES(258,'layanan_servis','min, bisa tune up motor','Bengkel melayani tune up motor.','');
INSERT INTO "chatbot_data" VALUES(259,'layanan_servis','min, bisa ganti ban','Bengkel melayani penggantian ban.','');
INSERT INTO "chatbot_data" VALUES(260,'layanan_servis','min, bisa ganti oli','Bengkel melayani penggantian oli.','');
INSERT INTO "chatbot_data" VALUES(261,'layanan_servis','min, bisa perbaiki rem motor','Bengkel melayani perbaikan rem motor.','');
INSERT INTO "chatbot_data" VALUES(262,'layanan_servis','min, servis motor karburator bisa','Bengkel melayani servis motor karburator.','');
INSERT INTO "chatbot_data" VALUES(263,'layanan_servis','min, servis motor beat bisa','Bengkel melayani servis motor Beat.','');
INSERT INTO "chatbot_data" VALUES(264,'layanan_servis','min, servis motor vario bisa','Bengkel melayani servis motor Vario.','');
INSERT INTO "chatbot_data" VALUES(265,'cek_stok','stok oli yamalube matic dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(266,'cek_stok','ada oli ahm mpx 2 dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(267,'cek_stok','oli enduro matic ready dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(268,'cek_stok','stok busi ngk cpr9ea dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(269,'cek_stok','ada busi denso u22epr9 dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(270,'cek_stok','stok aki gs astra dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(271,'cek_stok','aki yuasa masih ada dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(272,'cek_stok','ban fdr ready dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(273,'cek_stok','ban irc masih tersedia dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(274,'cek_stok','kampas rem federal ada dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(275,'cek_stok','kampas rem indoparts ready dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(276,'cek_stok','filter udara honda ada dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(277,'cek_stok','filter udara yamaha tersedia dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(278,'cek_stok','cvt belt bando ada dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(279,'cek_stok','rantai sss ready dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(280,'cek_stok','stok oli untuk beat dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(281,'cek_stok','stok busi untuk vario dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(282,'cek_stok','stok aki untuk scoopy dong','Sedang cek stok barang.','check_stock');
INSERT INTO "chatbot_data" VALUES(283,'info_barang','min, informasi oli yamalube matic','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(284,'info_barang','min, harga oli ahm mpx 2','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(285,'info_barang','min, detail oli enduro matic','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(286,'info_barang','min, info busi ngk cpr9ea','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(287,'info_barang','min, harga busi denso u22epr9','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(288,'info_barang','min, informasi aki gs astra','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(289,'info_barang','min, detail aki yuasa','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(290,'info_barang','min, harga ban fdr sport','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(291,'info_barang','min, info ban irc nr76','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(292,'info_barang','min, harga kampas rem federal','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(293,'info_barang','min, detail kampas rem indoparts','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(294,'info_barang','min, info filter udara honda','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(295,'info_barang','min, harga filter udara yamaha','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(296,'info_barang','min, detail cvt belt bando','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(297,'info_barang','min, harga rantai sss','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(298,'info_barang','min, harga oli untuk beat','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(299,'info_barang','min, info aki untuk vario','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(300,'info_barang','min, detail sparepart motor','Info barang.','info_barang');
INSERT INTO "chatbot_data" VALUES(301,'rekom_produk','oli yang cocok untuk beat dong','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(302,'rekom_produk','rekomendasi oli vario dong','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(303,'rekom_produk','oli bagus untuk scoopy dong','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(304,'rekom_produk','oli untuk motor matic dong','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(305,'rekom_produk','busi yang cocok untuk beat dong','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(306,'rekom_produk','busi untuk vario apa dong','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(307,'rekom_produk','aki terbaik untuk nmax dong','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(308,'rekom_produk','aki untuk pcx apa dong','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(309,'rekom_produk','ban yang cocok untuk beat dong','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(310,'rekom_produk','produk cocok untuk mio dong','Rekomendasi produk.','saran_produk');
INSERT INTO "chatbot_data" VALUES(311,'daftar_barang','oli yang tersedia ada apa saja dong','Berikut daftar oli yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(312,'daftar_barang','oli apa saja yang ada dong','Berikut daftar oli yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(313,'daftar_barang','daftar oli yang tersedia dong','Berikut daftar oli yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(314,'daftar_barang','pilihan oli di bengkel apa saja dong','Berikut daftar oli yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(315,'daftar_barang','busi yang tersedia ada apa saja dong','Berikut daftar busi yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(316,'daftar_barang','daftar aki yang ada dong','Berikut daftar aki yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(317,'daftar_barang','ban apa saja yang tersedia dong','Berikut daftar ban yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(318,'daftar_barang','sparepart yang tersedia apa saja dong','Berikut daftar sparepart yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(319,'daftar_barang','barang yang tersedia di bengkel apa saja dong','Berikut daftar barang yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(320,'daftar_barang','ada pilihan filter udara apa saja dong','Berikut daftar filter udara yang tersedia.','list_barang');
INSERT INTO "chatbot_data" VALUES(321,'layanan_servis','layanan apa saja yang ada di bengkel','Bengkel Kurnia Motor melayani berbagai jasa servis, antara lain: Servis Motor Matic, Servis Injeksi, Tune Up Motor, Ganti Ban, Ganti Oli, Perbaikan Rem Motor, dan Servis Motor Karburator.','');
INSERT INTO "chatbot_data" VALUES(322,'layanan_servis','bisa servis apa saja','Bengkel Kurnia Motor melayani berbagai jasa servis, antara lain: Servis Motor Matic, Servis Injeksi, Tune Up Motor, Ganti Ban, Ganti Oli, Perbaikan Rem Motor, dan Servis Motor Karburator.','');
INSERT INTO "chatbot_data" VALUES(323,'layanan_servis','daftar layanan bengkel','Bengkel Kurnia Motor melayani berbagai jasa servis, antara lain: Servis Motor Matic, Servis Injeksi, Tune Up Motor, Ganti Ban, Ganti Oli, Perbaikan Rem Motor, dan Servis Motor Karburator.','');
CREATE TABLE diagnosa_keluhan (
        id_diagnosa INTEGER PRIMARY KEY AUTOINCREMENT,
        kata_kunci TEXT NOT NULL UNIQUE,
        gejala TEXT NOT NULL,
        solusi_analisis TEXT NOT NULL
    );
INSERT INTO "diagnosa_keluhan" VALUES(1,'brebet gas','Motor brebet saat digas','Motor brebet saat digas biasanya disebabkan karburator atau injektor kotor.');
INSERT INTO "diagnosa_keluhan" VALUES(2,'brebet tanjakan','Motor brebet saat tanjakan','Motor brebet saat tanjakan biasanya karena suplai bahan bakar kurang optimal atau CVT mulai lemah.');
INSERT INTO "diagnosa_keluhan" VALUES(3,'brebet dingin','Motor brebet saat kondisi dingin','Motor brebet saat kondisi dingin biasanya karena busi atau setting udara belum optimal.');
INSERT INTO "diagnosa_keluhan" VALUES(4,'brebet','Motor brebet secara umum','Motor brebet dapat disebabkan oleh busi, karburator, injektor, atau filter udara.');
INSERT INTO "diagnosa_keluhan" VALUES(5,'mogok','Motor mogok / mati mendadak','Motor mogok bisa disebabkan aki lemah, busi bermasalah, suplai bensin tidak lancar, atau sistem pengapian terganggu.');
INSERT INTO "diagnosa_keluhan" VALUES(6,'rem','Masalah rem motor','Masalah rem bisa disebabkan kampas rem aus, setelan rem kurang tepat, atau komponen rem perlu dibersihkan.');
INSERT INTO "diagnosa_keluhan" VALUES(7,'asap','Asap putih dari knalpot','Asap putih dari motor biasanya berkaitan dengan oli yang ikut terbakar atau kondisi mesin yang perlu diperiksa.');
INSERT INTO "diagnosa_keluhan" VALUES(8,'bensin','Kehabisan bensin atau masalah bahan bakar','Jika motor kehabisan bensin, isi bahan bakar terlebih dahulu lalu coba starter ulang. Jika tetap bermasalah, sistem bahan bakar perlu dicek.');
INSERT INTO "diagnosa_keluhan" VALUES(9,'bunyi','Bunyi tidak normal pada motor','Bunyi tidak normal pada motor bisa berasal dari rantai, CVT, rem, atau bagian mesin. Sebaiknya dicek langsung agar sumber bunyinya jelas.');
INSERT INTO "diagnosa_keluhan" VALUES(10,'mogok starter','Motor mogok / starter tidak merespon (hanya bunyi cetek-cetek)','Motor tidak bisa distarter biasanya disebabkan oleh aki lemah, relay starter (bendik) rusak, atau tombol/switch starter kotor.');
INSERT INTO "diagnosa_keluhan" VALUES(11,'mogok kompresi','Motor mogok dan kick starter terasa sangat enteng (kehilangan kompresi)','Kondisi loss compression (hilang kompresi) biasanya memerlukan penambahan sedikit oli ke lubang busi untuk merapatkan klep kembali, atau servis besar untuk skir klep.');
INSERT INTO "diagnosa_keluhan" VALUES(12,'rem bunyi','Rem berdecit atau mengeluarkan suara berisik saat ditekan','Suara mendecit pada rem disebabkan oleh kampas rem yang kotor terkena debu jalanan atau kampas rem sudah tipis sehingga besi bergesekan dengan piringan cakram.');
INSERT INTO "diagnosa_keluhan" VALUES(13,'rem keras','Rem terasa keras atau macet saat ditekan','Rem keras atau macet biasanya disebabkan minyak rem yang kotor/berkurang, piston kaliper macet karena karat, atau terdapat angin palsu di sistem rem.');
INSERT INTO "diagnosa_keluhan" VALUES(14,'bunyi cvt','Bunyi kasar / berdecit di area CVT matic','Bunyi kasar di CVT matic umumnya disebabkan oleh roller yang sudah peang/aus, v-belt retak, atau bearing CVT yang mulai oblak.');
INSERT INTO "diagnosa_keluhan" VALUES(15,'bunyi rantai','Rantai berisik, kendor, atau terasa menyentak','Rantai berisik biasanya karena kering kurang pelumas, kendor, atau gir roda sudah tajam/aus. Solusinya lakukan pelumasan, penyetelan ulang, atau ganti gir set.');
INSERT INTO "diagnosa_keluhan" VALUES(16,'mesin panas','Mesin motor cepat panas atau terjadi overheat','Mesin cepat panas disebabkan oleh air radiator habis (pada motor radiator), kualitas oli menurun karena lama tidak diganti, atau volume oli mesin berkurang drastis.');
INSERT INTO "diagnosa_keluhan" VALUES(17,'asap hitam','Knalpot motor mengeluarkan asap hitam pekat','Asap hitam menandakan pembakaran terlalu boros, bisa karena filter udara kotor menyumbat pasokan oksigen, atau setelan karburator/injektor terlalu kaya bensin.');
INSERT INTO "diagnosa_keluhan" VALUES(18,'brebet panas','Motor brebet saat mesin panas','Motor brebet saat kondisi mesin panas biasanya karena koil pengapian mulai lemah/terlalu panas, atau setelan klep terlalu rapat sehingga tidak ada celah saat memuai.');
INSERT INTO "diagnosa_keluhan" VALUES(19,'brebet hujan','Motor brebet setelah kehujanan atau terkena air','Motor brebet setelah kehujanan atau terkena air biasanya disebabkan cop busi (cangklong busi) bocor sehingga air masuk, atau kabel pengapian terkelupas.');
INSERT INTO "diagnosa_keluhan" VALUES(20,'brebet atas','Motor brebet di putaran atas / RPM tinggi','Motor brebet pada putaran atas / RPM tinggi umumnya disebabkan main jet karburator tersumbat, filter udara sangat kotor, atau pasokan bahan bakar dari pompa bensin (fuel pump) melemah.');
INSERT INTO "diagnosa_keluhan" VALUES(21,'brebet bawah','Motor brebet di putaran bawah / langsam tidak stabil','Motor brebet pada putaran bawah / langsam tidak stabil biasanya karena pilot jet karburator tersumbat, setelan sekrup udara kurang pas, atau terjadi kebocoran udara di manifol karburator.');
INSERT INTO "diagnosa_keluhan" VALUES(22,'rem blong','Rem blong atau tidak pakem sama sekali','Rem blong atau tidak pakem disebabkan kampas rem habis total, minyak rem habis/bocor, piston kaliper macet karena karat, atau terjadi vapor lock (minyak rem mendidih).');
INSERT INTO "diagnosa_keluhan" VALUES(23,'stang goyang','Stang motor terasa goyang, tidak stabil, atau membuang ke samping','Stang terasa goyang atau tidak stabil biasanya karena komstir (steering head) yang aus/kendor, velg baling, ban benjol/kurang angin, atau bearing (laker) tromol roda oblak.');
INSERT INTO "diagnosa_keluhan" VALUES(24,'shock bocor','Shockbreaker keras, memantul berlebihan, atau bocor oli','Shockbreaker terasa keras atau memantul berlebihan disebabkan oleh oli shock bocor/habis, seal shock rusak, atau per suspensi sudah lemah sehingga suspensi mentok (bottoming).');
INSERT INTO "diagnosa_keluhan" VALUES(25,'aki tekor','Aki sering drop, tekor, atau tidak bisa menyimpan daya','Aki sering tekor umumnya disebabkan oleh sistem pengisian (kiprok/spool) yang bermasalah, adanya korsleting kabel (kebocoran arus), atau umur sel aki yang memang sudah habis.');
INSERT INTO "diagnosa_keluhan" VALUES(26,'kopling selip','Kopling terasa selip, tarikan mesin loyo, atau gigi susah masuk','Kopling selip atau tarikan mesin loyo disebabkan oleh kampas kopling yang aus/gosong, plat kopling melengkung, atau per kopling yang mulai melemah.');
INSERT INTO "diagnosa_keluhan" VALUES(27,'mesin ngelitik','Mesin berbunyi ngelitik (knocking) saat akselerasi atau digas','Mesin berbunyi ngelitik (knocking) umumnya disebabkan penggunaan bahan bakar dengan oktan terlalu rendah, penumpukan kerak karbon di ruang bakar, atau setelan celah klep yang terlalu renggang.');
CREATE TABLE "intent_templates" (
	"id"	INTEGER,
	"intent"	TEXT NOT NULL,
	"template_text"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "intent_templates" VALUES(1,'sapaan','halo');
INSERT INTO "intent_templates" VALUES(2,'sapaan','hai');
INSERT INTO "intent_templates" VALUES(3,'sapaan','hallo');
INSERT INTO "intent_templates" VALUES(4,'sapaan','selamat pagi');
INSERT INTO "intent_templates" VALUES(5,'sapaan','selamat siang');
INSERT INTO "intent_templates" VALUES(6,'sapaan','selamat sore');
INSERT INTO "intent_templates" VALUES(7,'sapaan','permisi');
INSERT INTO "intent_templates" VALUES(8,'sapaan','assalamualaikum');
INSERT INTO "intent_templates" VALUES(9,'sapaan','salam');
INSERT INTO "intent_templates" VALUES(10,'sapaan','pagi bengkel');
INSERT INTO "intent_templates" VALUES(11,'sapaan','halo bengkel');
INSERT INTO "intent_templates" VALUES(12,'sapaan','hei bengkel');
INSERT INTO "intent_templates" VALUES(13,'sapaan','hola bengkel');
INSERT INTO "intent_templates" VALUES(14,'sapaan','apa kabar bengkel');
INSERT INTO "intent_templates" VALUES(15,'sapaan','kabar baik');
INSERT INTO "intent_templates" VALUES(16,'sapaan','ada yang bisa dibantu');
INSERT INTO "intent_templates" VALUES(17,'sapaan','hai admin');
INSERT INTO "intent_templates" VALUES(18,'sapaan','pagi');
INSERT INTO "intent_templates" VALUES(19,'sapaan','siang');
INSERT INTO "intent_templates" VALUES(20,'sapaan','malam');
INSERT INTO "intent_templates" VALUES(21,'sapaan','halo semuanya');
INSERT INTO "intent_templates" VALUES(22,'sapaan','apa kabar');
INSERT INTO "intent_templates" VALUES(23,'sapaan','salam kenal');
INSERT INTO "intent_templates" VALUES(24,'sapaan','selamat datang');
INSERT INTO "intent_templates" VALUES(25,'sapaan','halo semua');
INSERT INTO "intent_templates" VALUES(26,'sapaan','hallo semua');
INSERT INTO "intent_templates" VALUES(27,'sapaan','assalamu''alaikum');
INSERT INTO "intent_templates" VALUES(28,'sapaan','syalom');
INSERT INTO "intent_templates" VALUES(29,'sapaan','salam sejahtera');
INSERT INTO "intent_templates" VALUES(30,'sapaan','pagi min');
INSERT INTO "intent_templates" VALUES(31,'sapaan','siang min');
INSERT INTO "intent_templates" VALUES(32,'sapaan','sore min');
INSERT INTO "intent_templates" VALUES(33,'sapaan','malam min');
INSERT INTO "intent_templates" VALUES(34,'sapaan','halo kurnia');
INSERT INTO "intent_templates" VALUES(35,'sapaan','hai kurnia');
INSERT INTO "intent_templates" VALUES(36,'sapaan','hallo kurnia');
INSERT INTO "intent_templates" VALUES(37,'sapaan','halo kak');
INSERT INTO "intent_templates" VALUES(38,'sapaan','pagi kak');
INSERT INTO "intent_templates" VALUES(39,'sapaan','siang kak');
INSERT INTO "intent_templates" VALUES(40,'sapaan','sore kak');
INSERT INTO "intent_templates" VALUES(41,'sapaan','malam kak');
INSERT INTO "intent_templates" VALUES(42,'sapaan','halo petugas');
INSERT INTO "intent_templates" VALUES(43,'sapaan','permisi petugas');
INSERT INTO "intent_templates" VALUES(44,'sapaan','punten mang');
INSERT INTO "intent_templates" VALUES(45,'sapaan','sampurasun');
INSERT INTO "intent_templates" VALUES(46,'sapaan','spada');
INSERT INTO "intent_templates" VALUES(47,'sapaan','permisi min');
INSERT INTO "intent_templates" VALUES(48,'sapaan','oi');
INSERT INTO "intent_templates" VALUES(49,'sapaan','oy');
INSERT INTO "intent_templates" VALUES(50,'bantuan_umum','tolong bantu saya');
INSERT INTO "intent_templates" VALUES(51,'bantuan_umum','bantu saya');
INSERT INTO "intent_templates" VALUES(52,'bantuan_umum','minta bantuan');
INSERT INTO "intent_templates" VALUES(53,'bantuan_umum','saya perlu bantuan');
INSERT INTO "intent_templates" VALUES(54,'bantuan_umum','kamu bisa bantu apa');
INSERT INTO "intent_templates" VALUES(55,'bantuan_umum','apa saja yang bisa dibantu');
INSERT INTO "intent_templates" VALUES(56,'bantuan_umum','fitur chatbot apa');
INSERT INTO "intent_templates" VALUES(57,'bantuan_umum','apa layananmu');
INSERT INTO "intent_templates" VALUES(58,'bantuan_umum','apa yang bisa kamu lakukan');
INSERT INTO "intent_templates" VALUES(59,'bantuan_umum','informasi apa saja tersedia');
INSERT INTO "intent_templates" VALUES(60,'bantuan_umum','tunjukkan apa yang bisa ditanyakan');
INSERT INTO "intent_templates" VALUES(61,'bantuan_umum','saya butuh informasi');
INSERT INTO "intent_templates" VALUES(62,'bantuan_umum','bantuan untuk bengkel');
INSERT INTO "intent_templates" VALUES(63,'bantuan_umum','bantu jawab pertanyaan bengkel');
INSERT INTO "intent_templates" VALUES(64,'bantuan_umum','chatbot ini bisa apa');
INSERT INTO "intent_templates" VALUES(65,'bantuan_umum','apakah kamu bisa bantu servis');
INSERT INTO "intent_templates" VALUES(66,'bantuan_umum','apakah kamu bisa bantu stok');
INSERT INTO "intent_templates" VALUES(67,'bantuan_umum','apakah kamu bisa bantu lokasi');
INSERT INTO "intent_templates" VALUES(68,'bantuan_umum','apa saja info bengkel');
INSERT INTO "intent_templates" VALUES(69,'bantuan_umum','bisa bantu masalah motor');
INSERT INTO "intent_templates" VALUES(70,'bantuan_umum','bisa tolong');
INSERT INTO "intent_templates" VALUES(71,'bantuan_umum','tolong infonya');
INSERT INTO "intent_templates" VALUES(72,'bantuan_umum','tanya dong');
INSERT INTO "intent_templates" VALUES(73,'bantuan_umum','tanya min');
INSERT INTO "intent_templates" VALUES(74,'bantuan_umum','mau tanya min');
INSERT INTO "intent_templates" VALUES(75,'bantuan_umum','bisa nanya');
INSERT INTO "intent_templates" VALUES(76,'akhir_percakapan','terima kasih');
INSERT INTO "intent_templates" VALUES(77,'akhir_percakapan','makasih');
INSERT INTO "intent_templates" VALUES(78,'akhir_percakapan','matur nuwun');
INSERT INTO "intent_templates" VALUES(79,'akhir_percakapan','sudah cukup');
INSERT INTO "intent_templates" VALUES(80,'akhir_percakapan','cukup');
INSERT INTO "intent_templates" VALUES(81,'akhir_percakapan','itu saja');
INSERT INTO "intent_templates" VALUES(82,'akhir_percakapan','sudah jelas');
INSERT INTO "intent_templates" VALUES(83,'akhir_percakapan','oke makasih');
INSERT INTO "intent_templates" VALUES(84,'akhir_percakapan','bye');
INSERT INTO "intent_templates" VALUES(85,'akhir_percakapan','sampai jumpa');
INSERT INTO "intent_templates" VALUES(86,'akhir_percakapan','sudah membantu');
INSERT INTO "intent_templates" VALUES(87,'akhir_percakapan','terima kasih banyak');
INSERT INTO "intent_templates" VALUES(88,'akhir_percakapan','mantap terima kasih');
INSERT INTO "intent_templates" VALUES(89,'akhir_percakapan','saya tutup');
INSERT INTO "intent_templates" VALUES(90,'akhir_percakapan','sampai ketemu lagi');
INSERT INTO "intent_templates" VALUES(91,'akhir_percakapan','thanks');
INSERT INTO "intent_templates" VALUES(92,'akhir_percakapan','selamat tinggal');
INSERT INTO "intent_templates" VALUES(93,'akhir_percakapan','baik terima kasih');
INSERT INTO "intent_templates" VALUES(94,'akhir_percakapan','cukup ya');
INSERT INTO "intent_templates" VALUES(95,'akhir_percakapan','cukup terima kasih');
INSERT INTO "intent_templates" VALUES(96,'akhir_percakapan','udah cukup');
INSERT INTO "intent_templates" VALUES(97,'jadwal_bengkel','bengkel buka jam berapa');
INSERT INTO "intent_templates" VALUES(98,'jadwal_bengkel','jam operasional bengkel');
INSERT INTO "intent_templates" VALUES(99,'jadwal_bengkel','hari ini buka tidak');
INSERT INTO "intent_templates" VALUES(100,'jadwal_bengkel','buka sampai jam berapa');
INSERT INTO "intent_templates" VALUES(101,'jadwal_bengkel','bengkel tutup jam berapa');
INSERT INTO "intent_templates" VALUES(102,'jadwal_bengkel','hari minggu buka tidak');
INSERT INTO "intent_templates" VALUES(103,'jadwal_bengkel','sabtu buka tidak');
INSERT INTO "intent_templates" VALUES(104,'jadwal_bengkel','bisa servis sore');
INSERT INTO "intent_templates" VALUES(105,'jadwal_bengkel','jadwal bengkel gimana');
INSERT INTO "intent_templates" VALUES(106,'jadwal_bengkel','buka dari pagi jam berapa');
INSERT INTO "intent_templates" VALUES(107,'jadwal_bengkel','bengkel libur hari apa');
INSERT INTO "intent_templates" VALUES(108,'jadwal_bengkel','masih buka sekarang');
INSERT INTO "intent_templates" VALUES(109,'jadwal_bengkel','apa jam kerja bengkel');
INSERT INTO "intent_templates" VALUES(110,'jadwal_bengkel','jam service bengkel');
INSERT INTO "intent_templates" VALUES(111,'jadwal_bengkel','apakah bengkel buka hari ini');
INSERT INTO "intent_templates" VALUES(112,'jadwal_bengkel','bengkel tutup kapan');
INSERT INTO "intent_templates" VALUES(113,'jadwal_bengkel','jam kerja bengkel hari ini');
INSERT INTO "intent_templates" VALUES(114,'jadwal_bengkel','bengkel buka sampai sore');
INSERT INTO "intent_templates" VALUES(115,'jadwal_bengkel','apa hari ini bengkel buka');
INSERT INTO "intent_templates" VALUES(116,'jadwal_bengkel','jadwal kerja bengkel');
INSERT INTO "intent_templates" VALUES(117,'lokasi_bengkel','alamat bengkel dimana');
INSERT INTO "intent_templates" VALUES(118,'lokasi_bengkel','lokasi bengkel dimana');
INSERT INTO "intent_templates" VALUES(119,'lokasi_bengkel','bengkel ada dimana');
INSERT INTO "intent_templates" VALUES(120,'lokasi_bengkel','share lokasi bengkel');
INSERT INTO "intent_templates" VALUES(121,'lokasi_bengkel','ada maps bengkel');
INSERT INTO "intent_templates" VALUES(122,'lokasi_bengkel','kirim alamat bengkel');
INSERT INTO "intent_templates" VALUES(123,'lokasi_bengkel','bengkel dekat mana');
INSERT INTO "intent_templates" VALUES(124,'lokasi_bengkel','rute ke bengkel gimana');
INSERT INTO "intent_templates" VALUES(125,'lokasi_bengkel','posisi bengkel dimana');
INSERT INTO "intent_templates" VALUES(126,'lokasi_bengkel','lokasi lengkap bengkel');
INSERT INTO "intent_templates" VALUES(127,'lokasi_bengkel','maps kurnia motor');
INSERT INTO "intent_templates" VALUES(128,'lokasi_bengkel','saya mau ke bengkel');
INSERT INTO "intent_templates" VALUES(129,'lokasi_bengkel','bagaimana menuju bengkel');
INSERT INTO "intent_templates" VALUES(130,'lokasi_bengkel','bengkel terdekat di mana');
INSERT INTO "intent_templates" VALUES(131,'lokasi_bengkel','lokasi bengkel terdekat');
INSERT INTO "intent_templates" VALUES(132,'lokasi_bengkel','di mana bengkel berada');
INSERT INTO "intent_templates" VALUES(133,'lokasi_bengkel','alamat bengkel kurnia');
INSERT INTO "intent_templates" VALUES(134,'lokasi_bengkel','bengkel motor kurnia dimana');
INSERT INTO "intent_templates" VALUES(135,'lokasi_bengkel','rute ke bengkel');
INSERT INTO "intent_templates" VALUES(136,'lokasi_bengkel','petunjuk arah bengkel');
INSERT INTO "intent_templates" VALUES(137,'kontak_admin','nomor wa bengkel berapa');
INSERT INTO "intent_templates" VALUES(138,'kontak_admin','wa bengkel berapa');
INSERT INTO "intent_templates" VALUES(139,'kontak_admin','nomor whatsapp bengkel');
INSERT INTO "intent_templates" VALUES(140,'kontak_admin','bisa hubungi lewat whatsapp');
INSERT INTO "intent_templates" VALUES(141,'kontak_admin','kontak admin ada');
INSERT INTO "intent_templates" VALUES(142,'kontak_admin','nomor telepon bengkel');
INSERT INTO "intent_templates" VALUES(143,'kontak_admin','minta nomor admin');
INSERT INTO "intent_templates" VALUES(144,'kontak_admin','saya mau chat petugas');
INSERT INTO "intent_templates" VALUES(145,'kontak_admin','hubungi petugas bengkel');
INSERT INTO "intent_templates" VALUES(146,'kontak_admin','nomor bengkel berapa');
INSERT INTO "intent_templates" VALUES(147,'kontak_admin','kontak bengkel');
INSERT INTO "intent_templates" VALUES(148,'kontak_admin','admin bisa dihubungi');
INSERT INTO "intent_templates" VALUES(149,'kontak_admin','bagaimana hubungi bengkel');
INSERT INTO "intent_templates" VALUES(150,'kontak_admin','ada nomor admin');
INSERT INTO "intent_templates" VALUES(151,'kontak_admin','nomor kontak bengkel');
INSERT INTO "intent_templates" VALUES(152,'kontak_admin','nomor cs bengkel');
INSERT INTO "intent_templates" VALUES(153,'kontak_admin','dapat nomor whatsapp bengkel');
INSERT INTO "intent_templates" VALUES(154,'kontak_admin','nomor hotline bengkel');
INSERT INTO "intent_templates" VALUES(155,'kontak_admin','hubungi bengkel lewat whatsapp');
INSERT INTO "intent_templates" VALUES(156,'kontak_admin','chat admin bengkel');
INSERT INTO "intent_templates" VALUES(157,'cek_stok','stok oli yamalube matic');
INSERT INTO "intent_templates" VALUES(158,'cek_stok','ada oli ahm mpx 2');
INSERT INTO "intent_templates" VALUES(159,'cek_stok','oli enduro matic ready');
INSERT INTO "intent_templates" VALUES(160,'cek_stok','cek stok oli');
INSERT INTO "intent_templates" VALUES(161,'cek_stok','ada stok aki motor');
INSERT INTO "intent_templates" VALUES(162,'cek_stok','stok ban depan ada');
INSERT INTO "intent_templates" VALUES(163,'cek_stok','apakah ada kampas rem');
INSERT INTO "intent_templates" VALUES(164,'cek_stok','stok busi iridium');
INSERT INTO "intent_templates" VALUES(165,'cek_stok','cek stok sparepart');
INSERT INTO "intent_templates" VALUES(166,'cek_stok','apakah ada oli matic');
INSERT INTO "intent_templates" VALUES(167,'cek_stok','ada stok oli motor');
INSERT INTO "intent_templates" VALUES(168,'cek_stok','stok bagian motor ada');
INSERT INTO "intent_templates" VALUES(169,'cek_stok','cek stok barang');
INSERT INTO "intent_templates" VALUES(170,'cek_stok','apakah barang ini tersedia');
INSERT INTO "intent_templates" VALUES(171,'cek_stok','stok oli, ban, aki');
INSERT INTO "intent_templates" VALUES(172,'cek_stok','ada aki gs astra');
INSERT INTO "intent_templates" VALUES(173,'cek_stok','stok filter udara');
INSERT INTO "intent_templates" VALUES(174,'cek_stok','ada barang untuk vario');
INSERT INTO "intent_templates" VALUES(175,'cek_stok','stok kampas kopling');
INSERT INTO "intent_templates" VALUES(176,'cek_stok','cek ketersediaan suku cadang');
INSERT INTO "intent_templates" VALUES(177,'daftar_barang','oli yang tersedia ada apa saja');
INSERT INTO "intent_templates" VALUES(178,'daftar_barang','oli apa saja yang ada');
INSERT INTO "intent_templates" VALUES(179,'daftar_barang','daftar oli yang tersedia');
INSERT INTO "intent_templates" VALUES(180,'daftar_barang','barang apa yang tersedia');
INSERT INTO "intent_templates" VALUES(181,'daftar_barang','jenis sparepart apa saja');
INSERT INTO "intent_templates" VALUES(182,'daftar_barang','daftar barang bengkel');
INSERT INTO "intent_templates" VALUES(183,'daftar_barang','produk apa saja ready');
INSERT INTO "intent_templates" VALUES(184,'daftar_barang','ada barang apa saat ini');
INSERT INTO "intent_templates" VALUES(185,'daftar_barang','apa saja stok yang tersedia');
INSERT INTO "intent_templates" VALUES(186,'daftar_barang','tunjukkan daftar barang');
INSERT INTO "intent_templates" VALUES(187,'daftar_barang','daftar suku cadang');
INSERT INTO "intent_templates" VALUES(188,'daftar_barang','daftar item bengkel');
INSERT INTO "intent_templates" VALUES(189,'daftar_barang','list barang bengkel');
INSERT INTO "intent_templates" VALUES(190,'daftar_barang','barang ready apa saja');
INSERT INTO "intent_templates" VALUES(191,'daftar_barang','apa saja item motor');
INSERT INTO "intent_templates" VALUES(192,'daftar_barang','barang senin tersedia');
INSERT INTO "intent_templates" VALUES(193,'daftar_barang','daftar jenis oli');
INSERT INTO "intent_templates" VALUES(194,'daftar_barang','daftar jenis aki');
INSERT INTO "intent_templates" VALUES(195,'daftar_barang','daftar komponen motor');
INSERT INTO "intent_templates" VALUES(196,'daftar_barang','daftar sparepart tersedia');
INSERT INTO "intent_templates" VALUES(197,'daftar_barang','daftar produk bengkel');
INSERT INTO "intent_templates" VALUES(198,'harga_servis','ganti oli motor berapa');
INSERT INTO "intent_templates" VALUES(199,'harga_servis','servis motor berapa');
INSERT INTO "intent_templates" VALUES(200,'harga_servis','servis lengkap habis berapa');
INSERT INTO "intent_templates" VALUES(201,'harga_servis','berapa harga servis');
INSERT INTO "intent_templates" VALUES(202,'harga_servis','biaya service motor');
INSERT INTO "intent_templates" VALUES(203,'harga_servis','berapa ongkos servis');
INSERT INTO "intent_templates" VALUES(204,'harga_servis','harga ganti aki berapa');
INSERT INTO "intent_templates" VALUES(205,'harga_servis','biaya ganti oli');
INSERT INTO "intent_templates" VALUES(206,'harga_servis','berapa biaya tune up');
INSERT INTO "intent_templates" VALUES(207,'harga_servis','harga servis motor matic');
INSERT INTO "intent_templates" VALUES(208,'harga_servis','berapa ongkos service');
INSERT INTO "intent_templates" VALUES(209,'harga_servis','harga servis full');
INSERT INTO "intent_templates" VALUES(210,'harga_servis','berapa harga perbaikan');
INSERT INTO "intent_templates" VALUES(211,'harga_servis','biaya service biasa');
INSERT INTO "intent_templates" VALUES(212,'harga_servis','harga service motor');
INSERT INTO "intent_templates" VALUES(213,'harga_servis','berapa biaya ganti ban');
INSERT INTO "intent_templates" VALUES(214,'harga_servis','harga servis berkala');
INSERT INTO "intent_templates" VALUES(215,'harga_servis','berapa biaya ganti kampas');
INSERT INTO "intent_templates" VALUES(216,'harga_servis','biaya servis rem');
INSERT INTO "intent_templates" VALUES(217,'harga_servis','harga servis motor kamu');
INSERT INTO "intent_templates" VALUES(218,'harga_servis','tarif tune up motor');
INSERT INTO "intent_templates" VALUES(219,'harga_servis','ongkos ganti oli berapa');
INSERT INTO "intent_templates" VALUES(220,'harga_servis','biaya perbaikan rem berapa');
INSERT INTO "intent_templates" VALUES(221,'harga_servis','habis berapa kalau servis');
INSERT INTO "intent_templates" VALUES(222,'harga_servis','servis injeksi bayar berapa');
INSERT INTO "intent_templates" VALUES(223,'harga_servis','ongkos pasang ban motor');
INSERT INTO "intent_templates" VALUES(224,'info_barang','informasi oli yamalube matic');
INSERT INTO "intent_templates" VALUES(225,'info_barang','harga oli ahm mpx 2');
INSERT INTO "intent_templates" VALUES(226,'info_barang','detail oli enduro matic');
INSERT INTO "intent_templates" VALUES(227,'info_barang','info oli terbaik');
INSERT INTO "intent_templates" VALUES(228,'info_barang','informasi barang');
INSERT INTO "intent_templates" VALUES(229,'info_barang','info sparepart');
INSERT INTO "intent_templates" VALUES(230,'info_barang','detail produk motor');
INSERT INTO "intent_templates" VALUES(231,'info_barang','apa spesifikasi oli');
INSERT INTO "intent_templates" VALUES(232,'info_barang','apa kelebihan oli ini');
INSERT INTO "intent_templates" VALUES(233,'info_barang','info aki gs astra');
INSERT INTO "intent_templates" VALUES(234,'info_barang','detail busi iridium');
INSERT INTO "intent_templates" VALUES(235,'info_barang','info komponen motor');
INSERT INTO "intent_templates" VALUES(236,'info_barang','detail kampas rem');
INSERT INTO "intent_templates" VALUES(237,'info_barang','informasi filter udara');
INSERT INTO "intent_templates" VALUES(238,'info_barang','info produk bengkel');
INSERT INTO "intent_templates" VALUES(239,'info_barang','detail produk sparepart');
INSERT INTO "intent_templates" VALUES(240,'info_barang','info suku cadang');
INSERT INTO "intent_templates" VALUES(241,'info_barang','informasi barang motor');
INSERT INTO "intent_templates" VALUES(242,'info_barang','detail minyak mesin');
INSERT INTO "intent_templates" VALUES(243,'info_barang','apa info oli');
INSERT INTO "intent_templates" VALUES(244,'info_barang','info sparepart motor');
INSERT INTO "intent_templates" VALUES(245,'layanan_servis','motor saya brebet');
INSERT INTO "intent_templates" VALUES(246,'layanan_servis','motor brebet saat digas');
INSERT INTO "intent_templates" VALUES(247,'layanan_servis','motor brebet di tanjakan');
INSERT INTO "intent_templates" VALUES(248,'layanan_servis','motor tidak hidup');
INSERT INTO "intent_templates" VALUES(249,'layanan_servis','motor mati mendadak');
INSERT INTO "intent_templates" VALUES(250,'layanan_servis','motor susah distart');
INSERT INTO "intent_templates" VALUES(251,'layanan_servis','motor tersendat');
INSERT INTO "intent_templates" VALUES(252,'layanan_servis','motor kurang tenaga');
INSERT INTO "intent_templates" VALUES(253,'layanan_servis','motor ngelitik');
INSERT INTO "intent_templates" VALUES(254,'layanan_servis','knalpot motor bunyi');
INSERT INTO "intent_templates" VALUES(255,'layanan_servis','rem blong');
INSERT INTO "intent_templates" VALUES(256,'layanan_servis','ban bocor');
INSERT INTO "intent_templates" VALUES(257,'layanan_servis','motor panas terus');
INSERT INTO "intent_templates" VALUES(258,'layanan_servis','motor hidup mati hidup');
INSERT INTO "intent_templates" VALUES(259,'layanan_servis','motor mogok');
INSERT INTO "intent_templates" VALUES(260,'layanan_servis','motor tarikan lemah');
INSERT INTO "intent_templates" VALUES(261,'layanan_servis','motor bergetar');
INSERT INTO "intent_templates" VALUES(262,'layanan_servis','motor spin gas');
INSERT INTO "intent_templates" VALUES(263,'layanan_servis','motor gas tidak stabil');
INSERT INTO "intent_templates" VALUES(264,'layanan_servis','motor susah gas');
INSERT INTO "intent_templates" VALUES(265,'layanan_servis','layanan apa saja yang ada di bengkel');
INSERT INTO "intent_templates" VALUES(266,'layanan_servis','bisa servis apa saja');
INSERT INTO "intent_templates" VALUES(267,'layanan_servis','daftar layanan bengkel');
INSERT INTO "intent_templates" VALUES(268,'layanan_servis','apa saja jasa servis di sini');
INSERT INTO "intent_templates" VALUES(269,'layanan_servis','layanan di kurnia motor');
INSERT INTO "intent_templates" VALUES(270,'layanan_servis','bisa servis apa aja');
INSERT INTO "intent_templates" VALUES(271,'layanan_servis','layanan servis motor');
INSERT INTO "intent_templates" VALUES(272,'layanan_servis','bisa service apa aja');
INSERT INTO "intent_templates" VALUES(273,'layanan_servis','apa saja layanan bengkel');
INSERT INTO "intent_templates" VALUES(274,'layanan_servis','layanan bengkel');
INSERT INTO "intent_templates" VALUES(275,'rekom_produk','oli yang cocok untuk beat');
INSERT INTO "intent_templates" VALUES(276,'rekom_produk','rekomendasi oli vario');
INSERT INTO "intent_templates" VALUES(277,'rekom_produk','oli bagus untuk scoopy');
INSERT INTO "intent_templates" VALUES(278,'rekom_produk','pilih oli untuk nmax');
INSERT INTO "intent_templates" VALUES(279,'rekom_produk','pilih oli terbaik untuk honda');
INSERT INTO "intent_templates" VALUES(280,'rekom_produk','rekomendasi oli matic');
INSERT INTO "intent_templates" VALUES(281,'rekom_produk','oli untuk motor matik');
INSERT INTO "intent_templates" VALUES(282,'rekom_produk','rekomendasi produk motor');
INSERT INTO "intent_templates" VALUES(283,'rekom_produk','apa oli terbaik');
INSERT INTO "intent_templates" VALUES(284,'rekom_produk','saran oli untuk vario');
INSERT INTO "intent_templates" VALUES(285,'rekom_produk','oli matic apa yang cocok');
INSERT INTO "intent_templates" VALUES(286,'rekom_produk','saran produk motor');
INSERT INTO "intent_templates" VALUES(287,'rekom_produk','mana oli yang cocok');
INSERT INTO "intent_templates" VALUES(288,'rekom_produk','apa oli untuk beat');
INSERT INTO "intent_templates" VALUES(289,'rekom_produk','rekomendasi aki');
INSERT INTO "intent_templates" VALUES(290,'rekom_produk','apa produk terbaik untuk motor');
INSERT INTO "intent_templates" VALUES(291,'rekom_produk','saran oli honda');
INSERT INTO "intent_templates" VALUES(292,'rekom_produk','rekomendasi sparepart');
INSERT INTO "intent_templates" VALUES(293,'rekom_produk','apa oli ideal untuk nmax');
INSERT INTO "intent_templates" VALUES(294,'rekom_produk','saran oli mesin');
CREATE TABLE "kategori_barang" (
	"id_kategori"	INTEGER,
	"nama_kategori"	TEXT NOT NULL,
	PRIMARY KEY("id_kategori" AUTOINCREMENT)
);
INSERT INTO "kategori_barang" VALUES(1,'oli');
INSERT INTO "kategori_barang" VALUES(2,'busi');
INSERT INTO "kategori_barang" VALUES(3,'aki');
INSERT INTO "kategori_barang" VALUES(4,'ban');
INSERT INTO "kategori_barang" VALUES(5,'kampas rem');
INSERT INTO "kategori_barang" VALUES(6,'sparepart');
INSERT INTO "kategori_barang" VALUES(7,'filter udara');
INSERT INTO "kategori_barang" VALUES(8,'lampu');
INSERT INTO "kategori_barang" VALUES(9,'filter oli');
INSERT INTO "kategori_barang" VALUES(10,'kampas kopling');
INSERT INTO "kategori_barang" VALUES(11,'knalpot');
INSERT INTO "kategori_barang" VALUES(12,'spion');
INSERT INTO "kategori_barang" VALUES(13,'roller');
INSERT INTO "kategori_barang" VALUES(14,'switch');
INSERT INTO "kategori_barang" VALUES(15,'starter motor');
INSERT INTO "kategori_barang" VALUES(16,'karburator');
INSERT INTO "kategori_barang" VALUES(17,'cdi');
INSERT INTO "kategori_barang" VALUES(18,'rem cakram');
INSERT INTO "kategori_barang" VALUES(19,'velg');
INSERT INTO "kategori_barang" VALUES(20,'rantai');
CREATE TABLE log_chat (

    id_chat INTEGER PRIMARY KEY AUTOINCREMENT,

    pertanyaan TEXT NOT NULL,

    intent TEXT,

    jawaban TEXT,

    waktu DATETIME DEFAULT CURRENT_TIMESTAMP
, klasifikasi TEXT, pertanyaan_normalisasi TEXT);
CREATE TABLE riwayat_stok (

    id_riwayat INTEGER PRIMARY KEY AUTOINCREMENT,

    id_admin INTEGER NOT NULL,

    id_barang INTEGER NOT NULL,

    aksi TEXT NOT NULL,

    stok_lama INTEGER,

    stok_baru INTEGER,

    tanggal DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (id_admin) REFERENCES users(id_admin),

    FOREIGN KEY (id_barang) REFERENCES barang(id_barang)
);
CREATE TABLE "users" (
	"id_admin"	INTEGER,
	"username"	TEXT NOT NULL,
	"password"	TEXT NOT NULL,
	PRIMARY KEY("id_admin" AUTOINCREMENT)
);
INSERT INTO "users" VALUES(1,'admin1','pbkdf2:sha256:1000000$l2dkXT8I8OMqyXys$89b3b07c0271893c39aef56f4836a39b208ea716844cf89c7bb470011b755fa2');
INSERT INTO "users" VALUES(2,'admin2','pbkdf2:sha256:1000000$l2dkXT8I8OMqyXys$89b3b07c0271893c39aef56f4836a39b208ea716844cf89c7bb470011b755fa2');
INSERT INTO "users" VALUES(3,'admin3','pbkdf2:sha256:1000000$l2dkXT8I8OMqyXys$89b3b07c0271893c39aef56f4836a39b208ea716844cf89c7bb470011b755fa2');
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('intent_templates',294);
INSERT INTO "sqlite_sequence" VALUES('barang',48);
INSERT INTO "sqlite_sequence" VALUES('users',3);
INSERT INTO "sqlite_sequence" VALUES('kategori_barang',20);
INSERT INTO "sqlite_sequence" VALUES('log_chat',107);
INSERT INTO "sqlite_sequence" VALUES('riwayat_stok',5);
INSERT INTO "sqlite_sequence" VALUES('chatbot_data',323);
INSERT INTO "sqlite_sequence" VALUES('diagnosa_keluhan',27);
COMMIT;
